scrollAreaStyle = (
    "*{\n"
    "    background-color:  #DDE6ED\n"
    "\n"
    "}\n"
    "/*VERTICAL SCROLLBAR */ \n"
    "QScrollBar:vertical { \n"
    "    border: none;\n"
    "    background-color: rgb(255,255,255);\n"
    "    width: 14px;\n"
    "    margin: 15px 0 15px 0;\n"
    "    border-radius: 0px;\n"
    "}\n"
    "/*HANDLE BAR VERTICAL */\n"
    " QScrollBar::handle:vertical {\n"
    "    background-color: #005ef4; \n"
    "    min-height: 30px;\n"
    "    border-radius: 7px;\n"
    "}\n"
    "QScrollBar::handle:vertical:hover{ \n"
    "    background-color: #394867;\n"
    "}\n"
    "\n"
    "/*BTN TOP-SCROLLBAR */ \n"
    "QScrollBar::sub-line:vertical { \n"
    "    border: none;\n"
    "    background-color: #005ef4; \n"
    "    height: 15px;\n"
    "    border-top-left-radius: 7px; \n"
    "    border-top-right-radius: 7px; \n"
    "    subcontrol-position: top;\n"
    "    subcontrol-origin: margin;\n"
    "}\n"
    "\n"
    "/*BTN BOTTOM-SCROLLBAR */\n"
    "QScrollBar::add-line:vertical { \n"
    "    border: none;\n"
    "    background-color: #005ef4; \n"
    "    height: 15px;\n"
    "    border-bottom-left-radius: 7px; \n"
    "    border-bottom-right-radius: 7px;\n"
    "    subcontrol-position: bottom;\n"
    "    subcontrol-origin: margin;\n"
    "}\n"
    "QScrollBar::add-line:vertical:hover, QScrollBar::sub-line:vertical:hover, QScrollBar::sub-line:vertical:pressed, QScrollBar::add-line:vertical:pressed { \n"
    "    background-color: rgb(59, 59, 90);\n"
    "}\n"
    "\n"
    "/*reset arrows*/\n"
    "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
    "     background: none;\n"
    "}\n"
    "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical { \n"
    "    background: none;\n"
    "}"
)
hWidStyle = "background-color:white;\n" "border-radius:10px;\n" "padding:10px;\n" ""

lineEditStyle = (
    "QLineEdit{\n"
    "    background-color:#DDE6ED;\n"
    "}\n"
    "\n"
    "QLineEdit:focus {\n"
    "    border: 2px solid #005ef4;\n"
    "\n"
    "}"
)
queryStyle = (
    "QLabel{\n"
    "background-color: #eff2f9;\n"
    "border-top-left-radius :30px;\n"
    "border-top-right-radius : 20px; \n"
    "border-bottom-left-radius : 30px; \n"
    "margin:10px;\n"
    "}\n"
    "QLabel:hover{\n"
    "background-color: rgb(217, 229, 240);\n"
    "border:1px solid white;\n"
    "}"
)
replyStyle = (
    "QLabel{background-color:#005ef4;\n"
    "color:white;\n"
    "border-top-left-radius :20px;\n"
    "border-top-right-radius : 30px; \n"
    "border-bottom-right-radius : 30px; \n"
    "margin:10px;\n"
    "}\n"
    "QLabel:hover{\n"
    "background-color: #0087f4;\n"
    "border:1px solid white;\n"
    "}"
)
btnStyle = (
    "QPushButton{\n"
    "    color: #132d52;\n"
    "    background-color:#DDE6ED;\n"
    "    border:none;\n"
    "    border-radius:5%;\n"
    "}\n"
    "QPushButton:hover{\n"
    "    border:2px solid #005ef4;\n"
    "}\n"
    "QPushButton:pressed{\n"
    "    border:4px solid black;\n"
    "}\n"
    "\n"
    ""
)
